apiVersion: v1
kind: Pod
metadata:
  name: memory-limit-pod
spec:
  containers:
  - name: memory-limit-container
    image: progrium/stress
    command: ["/usr/bin/stress"]
    args:
    - "--vm"
    - "1"
    - "--vm-bytes"
    - "256M"
    - "--vm-hang"
    - "0"
    - "--timeout"
    - "60s"
    resources:
      limits:
        memory: "128Mi"
      requests:
        memory: "64Mi"
